# Generated by Django 4.2.6 on 2023-10-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=200, verbose_name="IP")),
                ("link", models.CharField(max_length=10000, verbose_name="Link")),
                ("uuid", models.CharField(max_length=10, verbose_name="UUID")),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
