# Generated by Django 4.2.6 on 2023-10-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="expire",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Expire"),
        ),
    ]
