# Generated by Django 4.2.6 on 2023-10-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortner", "0002_url_expire"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="is_expire",
            field=models.BooleanField(default=False, verbose_name="Is Expire"),
        ),
    ]
