# Generated by Django 4.2.6 on 2023-10-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortner", "0003_url_is_expire"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=200, verbose_name="Phone")),
                ("otp", models.CharField(max_length=50, verbose_name="OTP")),
                (
                    "expire_otp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expire OTP"
                    ),
                ),
                ("ip", models.CharField(max_length=200, verbose_name="Last IP")),
                (
                    "account",
                    models.CharField(
                        choices=[("n", "Normal"), ("p", "premium")],
                        default="n",
                        max_length=1,
                        verbose_name="Account Type",
                    ),
                ),
                (
                    "expire_premium",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expire Premium"
                    ),
                ),
            ],
        ),
    ]
