# Generated by Django 4.2.6 on 2023-10-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortner", "0004_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[("a", "Active"), ("d", "Deactive"), ("b", "Banned")],
                default="d",
                max_length=1,
                verbose_name="Status",
            ),
        ),
    ]
